ITALY_DAYS = [
    {
        "title": "Rome arrival · Centro Storico",
        "items": [
            (
                "Pantheon",
                "Historic landmark",
                "must",
                "10:00",
                75,
                "Piazza della Rotonda, Rome",
                "https://www.pantheonroma.com/",
            ),
            (
                "Piazza Navona",
                "Public square",
                "recommended",
                "12:00",
                60,
                "Piazza Navona, Rome",
                "https://www.turismoroma.it/en/places/navona-square",
            ),
            (
                "Trevi Fountain",
                "Historic landmark",
                "must",
                "16:30",
                60,
                "Piazza di Trevi, Rome",
                "https://www.turismoroma.it/en/places/trevi-fountain",
            ),
            (
                "Trastevere food walk",
                "Food & neighborhood",
                "flexible",
                "19:00",
                120,
                "Piazza di Santa Maria in Trastevere, Rome",
                "https://www.turismoroma.it/en/quartieri/trastevere",
            ),
        ],
    },
    {
        "title": "Ancient Rome",
        "items": [
            (
                "Colosseum",
                "Archaeology",
                "must",
                "08:30",
                120,
                "Piazza del Colosseo, Rome",
                "https://colosseo.it/en/",
            ),
            (
                "Roman Forum and Palatine Hill",
                "Archaeology",
                "must",
                "11:00",
                150,
                "Via della Salara Vecchia, Rome",
                "https://colosseo.it/en/area/the-roman-forum/",
            ),
            (
                "Capitoline Museums",
                "Museum",
                "recommended",
                "15:30",
                120,
                "Piazza del Campidoglio, Rome",
                "https://www.museicapitolini.org/en",
            ),
            (
                "Monti neighborhood",
                "Neighborhood",
                "flexible",
                "18:30",
                90,
                "Via del Boschetto, Rome",
                "https://www.turismoroma.it/en/quartieri/monti",
            ),
        ],
    },
    {
        "title": "Vatican City",
        "items": [
            (
                "Vatican Museums and Sistine Chapel",
                "Museum",
                "must",
                "08:00",
                210,
                "Viale Vaticano, Vatican City",
                "https://www.museivaticani.va/",
            ),
            (
                "St. Peter’s Basilica",
                "Religious landmark",
                "must",
                "12:30",
                120,
                "Piazza San Pietro, Vatican City",
                "https://www.basilicasanpietro.va/",
            ),
            (
                "Castel Sant’Angelo",
                "Museum & viewpoint",
                "recommended",
                "16:00",
                120,
                "Lungotevere Castello, Rome",
                "https://castelsantangelo.beniculturali.it/",
            ),
            (
                "Prati dinner",
                "Food & neighborhood",
                "flexible",
                "19:00",
                90,
                "Via Cola di Rienzo, Rome",
                "https://www.turismoroma.it/en/quartieri/prati",
            ),
        ],
    },
    {
        "title": "Florence essentials",
        "items": [
            (
                "Cathedral of Santa Maria del Fiore",
                "Architecture",
                "must",
                "09:00",
                150,
                "Piazza del Duomo, Florence",
                "https://duomo.firenze.it/en/home",
            ),
            (
                "Uffizi Galleries",
                "Art museum",
                "must",
                "12:00",
                180,
                "Piazzale degli Uffizi, Florence",
                "https://www.uffizi.it/en/the-uffizi",
            ),
            (
                "Ponte Vecchio",
                "Historic bridge",
                "recommended",
                "16:30",
                60,
                "Ponte Vecchio, Florence",
                "https://www.feelflorence.it/en/points-interest/ponte-vecchio",
            ),
            (
                "Oltrarno artisan walk",
                "Neighborhood",
                "flexible",
                "18:00",
                90,
                "Piazza Santo Spirito, Florence",
                "https://www.feelflorence.it/en",
            ),
        ],
    },
    {
        "title": "Florence art and viewpoints",
        "items": [
            (
                "Galleria dell’Accademia",
                "Art museum",
                "must",
                "08:30",
                120,
                "Via Ricasoli, Florence",
                "https://www.galleriaaccademiafirenze.it/en/",
            ),
            (
                "Basilica of Santa Croce",
                "Religious landmark",
                "recommended",
                "11:30",
                90,
                "Piazza di Santa Croce, Florence",
                "https://www.santacroceopera.it/en/",
            ),
            (
                "Boboli Gardens",
                "Historic garden",
                "recommended",
                "14:30",
                150,
                "Piazza de' Pitti, Florence",
                "https://www.uffizi.it/en/boboli-garden",
            ),
            (
                "Piazzale Michelangelo",
                "Viewpoint",
                "must",
                "18:30",
                90,
                "Piazzale Michelangelo, Florence",
                "https://www.feelflorence.it/en/points-interest/piazzale-michelangelo",
            ),
        ],
    },
    {
        "title": "Siena and Tuscan hill towns",
        "items": [
            (
                "Piazza del Campo",
                "Historic square",
                "must",
                "09:30",
                75,
                "Piazza del Campo, Siena",
                "https://www.visittuscany.com/en/attractions/piazza-del-campo-in-siena/",
            ),
            (
                "Siena Cathedral",
                "Architecture",
                "must",
                "11:00",
                120,
                "Piazza del Duomo, Siena",
                "https://operaduomo.siena.it/en/",
            ),
            (
                "San Gimignano historic center",
                "Hill town",
                "recommended",
                "14:30",
                180,
                "Piazza della Cisterna, San Gimignano",
                "https://www.sangimignano.com/en/",
            ),
            (
                "Tuscan countryside dinner",
                "Food & landscape",
                "flexible",
                "19:00",
                120,
                "Chianti, Tuscany",
                "https://www.visittuscany.com/en/",
            ),
        ],
    },
    {
        "title": "Venice icons",
        "items": [
            (
                "St. Mark’s Basilica",
                "Religious landmark",
                "must",
                "09:00",
                90,
                "Piazza San Marco, Venice",
                "https://www.basilicasanmarco.it/en/",
            ),
            (
                "Doge’s Palace",
                "Museum",
                "must",
                "11:00",
                150,
                "Piazza San Marco, Venice",
                "https://palazzoducale.visitmuve.it/en/home/",
            ),
            (
                "Rialto Bridge and market",
                "Market & landmark",
                "recommended",
                "15:00",
                90,
                "Ponte di Rialto, Venice",
                "https://www.veneziaunica.it/en",
            ),
            (
                "Dorsoduro evening walk",
                "Neighborhood",
                "flexible",
                "18:30",
                120,
                "Dorsoduro, Venice",
                "https://www.veneziaunica.it/en",
            ),
        ],
    },
    {
        "title": "Venetian lagoon islands",
        "items": [
            (
                "Murano Glass Museum",
                "Museum & craft",
                "recommended",
                "09:30",
                120,
                "Fondamenta Marco Giustinian, Murano",
                "https://museovetro.visitmuve.it/en/home/",
            ),
            (
                "Burano island",
                "Island & photography",
                "must",
                "12:30",
                180,
                "Burano, Venice",
                "https://www.veneziaunica.it/en/content/burano",
            ),
            (
                "Torcello Basilica",
                "Historic landmark",
                "flexible",
                "16:00",
                90,
                "Piazza Torcello, Venice",
                "https://www.veneziaunica.it/en/content/torcello",
            ),
            (
                "Cannaregio cicchetti walk",
                "Food & neighborhood",
                "recommended",
                "19:00",
                120,
                "Fondamenta della Misericordia, Venice",
                "https://www.veneziaunica.it/en",
            ),
        ],
    },
    {
        "title": "Venice art and departure",
        "items": [
            (
                "Peggy Guggenheim Collection",
                "Modern art museum",
                "must",
                "10:00",
                120,
                "Dorsoduro 701, Venice",
                "https://www.guggenheim-venice.it/en/",
            ),
            (
                "Gallerie dell’Accademia",
                "Art museum",
                "recommended",
                "12:30",
                150,
                "Campo della Carità, Venice",
                "https://www.gallerieaccademia.it/en",
            ),
            (
                "Scuola Grande di San Rocco",
                "Art & architecture",
                "flexible",
                "15:30",
                90,
                "San Polo, Venice",
                "https://www.scuolagrandesanrocco.org/home-en/",
            ),
            (
                "Grand Canal vaporetto ride",
                "Scenic transit",
                "must",
                "17:30",
                75,
                "Ferrovia vaporetto stop, Venice",
                "https://actv.avmspa.it/en",
            ),
        ],
    },
]
