"use client";

import { ChangeEvent, DragEvent, useRef, useState } from "react";
import { AppShell } from "../../components/AppShell";
import { PageHeader } from "../../components/Cards";
import { validateFile } from "../../lib/validation";

type Upload = { id: string; name: string; type: string; size: number; progress: number; status: "uploading" | "ready" | "error"; error?: string };
export default function Documents() { const [files, setFiles] = useState<Upload[]>([{ id: "seed", name: "Alex_Morgan_Resume.pdf", type: "PDF", size: 482000, progress: 100, status: "ready" }]); const input = useRef<HTMLInputElement>(null); function receive(list: FileList | null) { if (!list) return; Array.from(list).slice(0, 5).forEach(file => { const error = validateFile(file); const item: Upload = { id: crypto.randomUUID(), name: file.name, type: file.name.split(".").pop()?.toUpperCase() ?? "FILE", size: file.size, progress: error ? 0 : 15, status: error ? "error" : "uploading", error: error ?? undefined }; setFiles(current => [...current, item]); if (!error) { const timer = setInterval(() => setFiles(current => current.map(x => x.id === item.id ? { ...x, progress: Math.min(x.progress + 25, 100), status: x.progress >= 75 ? "ready" : "uploading" } : x)), 220); setTimeout(() => clearInterval(timer), 1000); } }); } function drop(event: DragEvent) { event.preventDefault(); receive(event.dataTransfer.files); } return <AppShell><main className="page"><PageHeader eyebrow="SECURE KNOWLEDGE" title="Documents" description="Documents are scoped to your workspace. The MVP simulates signed object-storage uploads."/><section className="upload" onDragOver={e => e.preventDefault()} onDrop={drop} onClick={() => input.current?.click()}><input ref={input} hidden multiple type="file" accept=".pdf,.jpg,.jpeg,.png,.docx" onChange={(e: ChangeEvent<HTMLInputElement>) => receive(e.target.files)}/><div>⇧</div><h3>Drop files here or choose files</h3><p>PDF, JPG, PNG, or DOCX · Up to 10 MB · Maximum 5 at a time</p><button className="secondary">Choose files</button></section><section className="panel"><div className="panel-head"><div><p className="eyebrow">YOUR FILES</p><h2>{files.length} documents</h2></div></div><div className="file-list">{files.map(file => <article key={file.id}><span className="file-icon">▱</span><div className="file-info"><b>{file.name}</b><small>{file.type} · {(file.size / 1024).toFixed(0)} KB</small>{file.status === "uploading" && <div className="progress"><span style={{width:`${file.progress}%`}}/></div>}{file.error && <em>{file.error}</em>}</div><span className={`file-status ${file.status}`}>{file.status === "ready" ? "✓ Ready" : file.status === "error" ? "Failed" : `${file.progress}%`}</span><button className="remove" aria-label={`Remove ${file.name}`} onClick={() => setFiles(files.filter(x => x.id !== file.id))}>×</button></article>)}</div></section></main></AppShell>; }
